Tree.hash = #568AF2
Tree.selectionBackground = #3E6CAD

Slider.trackColor = #616365

SplitPaneDivider.hoverColor = lighten(@background, 5%)

# Custom OpenRocket keys
OR.ScrollPane.borderColor = #6e7275
OR.colors.background = #2b2d33
OR.colors.border = #a3a3a3cc
OR.colors.text = $Label.foreground
OR.colors.text.dim = #a5abb8
OR.colors.text.disabled = #808080df
OR.colors.textSelection.foreground = #ffffff
OR.colors.textSelection.background = #3e6cad
OR.colors.info = #c5c5fc
OR.colors.warning = #ffe9bb
OR.colors.error = #ffadad
OR.colors.darkError = #ffb2b2
OR.colors.row.lighter = #2b313a
OR.colors.row.darker = #22252c
OR.colors.table.flash = #ffff803c
OR.colors.table.selection = #334266
OR.colors.flightData.textActive = #d4e6ff
OR.colors.flightData.textInactive = #aac9ff7f
OR.colors.multiCompEdit = #ffa5c8
OR.defaults.component.body = 150,175,255
OR.defaults.component.tubeFinSet = 150,184,254
OR.defaults.component.finSet = 150,184,255
OR.defaults.component.launchLug = 142,153,238
OR.defaults.component.railButton = 142,153,238
OR.defaults.component.internal = 181,128,151
OR.defaults.component.massObject = 210,210,210
OR.defaults.component.recoveryDevice = 220,90,90
OR.defaults.component.podSet = 190,190,235
OR.defaults.component.parallelStage = 210,180,195
OR.defaults.lineStyle.generic = SOLID
OR.defaults.lineStyle.massObject = DASHED
OR.colors.motor.border = #ffffffc8
OR.colors.motor.fill = #00000046
OR.colors.cg = #5585fd
OR.colors.cp = #ff486a
OR.colors.url = #abb9ff
OR.colors.componentTree.background = #2b2d33
OR.colors.componentTree.foreground = $Label.foreground
OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.dark
OR.colors.fin.gridMajor = #a4a4e0c5
OR.colors.fin.gridMinor = #8686c945
OR.colors.fin.point = #f27979ff
OR.colors.fin.selectedPoint = #e84e4eff
OR.colors.fin.bodyLine = #ffffff
OR.colors.fin.snapHighlight = #f14d4dff
