OR.colors.background = #2b2d33
OR.colors.border = #a3a3a3cc
OR.colors.text = $Label.foreground
OR.colors.text.dim = #a5abb8
OR.colors.text.disabled = #808080df
OR.colors.textSelection.foreground = #ffffff
OR.colors.textSelection.background = #3e6cad
OR.colors.info = #c5c5fc
OR.colors.warning = #ffe9bb
OR.colors.error = #ffadad
OR.colors.darkError = #ffb2b2
OR.colors.row.lighter = #2b313a
OR.colors.row.darker = #22252c
OR.colors.table.flash = #ffff803c
OR.colors.table.selection = #334266
OR.colors.flightData.textActive = #d4e6ff
OR.colors.flightData.textInactive = #aac9ff7f
OR.colors.multiCompEdit = #ffa5c8
OR.defaults.component.body = 150,175,255
OR.defaults.component.tubeFinSet = 150,184,254
OR.defaults.component.finSet = 150,184,255
OR.defaults.component.launchLug = 142,153,238
OR.defaults.component.railButton = 142,153,238
OR.defaults.component.internal = 181,128,151
OR.defaults.component.massObject = 210,210,210
OR.defaults.component.recoveryDevice = 220,90,90
OR.defaults.component.podSet = 190,190,235
OR.defaults.component.parallelStage = 210,180,195
OR.defaults.lineStyle.generic = SOLID
OR.defaults.lineStyle.massObject = DASHED
OR.colors.motor.border = #ffffffc8
OR.colors.motor.fill = #00000046
OR.colors.cg = #5585fd
OR.colors.cp = #ff486a
OR.colors.url = #abb9ff
OR.colors.componentTree.background = #2b2d33
OR.colors.componentTree.foreground = $Label.foreground
OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.dark
OR.colors.fin.gridMajor = #a4a4e0c5
OR.colors.fin.gridMinor = #8686c945
OR.colors.fin.point = #f27979ff
OR.colors.fin.selectedPoint = #e84e4eff
OR.colors.fin.bodyLine = #ffffff
OR.colors.fin.snapHighlight = #f14d4dff

[One Dark]Tree.hash = #568AF2
[One Dark]Tree.selectionBackground = #3E6CAD

[One Dark]Slider.trackColor = #616365

[One Dark]SplitPaneDivider.hoverColor = lighten(@background, 5%)

# Custom OpenRocket keys
[One Dark]OR.ScrollPane.borderColor = #6e7275
[One Dark]OR.colors.background = #2b2d33
[One Dark]OR.colors.border = #a3a3a3cc
[One Dark]OR.colors.text = $Label.foreground
[One Dark]OR.colors.text.dim = #a5abb8
[One Dark]OR.colors.text.disabled = #808080df
[One Dark]OR.colors.textSelection.foreground = #ffffff
[One Dark]OR.colors.textSelection.background = #3e6cad
[One Dark]OR.colors.info = #c5c5fc
[One Dark]OR.colors.warning = #ffe9bb
[One Dark]OR.colors.error = #ffadad
[One Dark]OR.colors.darkError = #ffb2b2
[One Dark]OR.colors.row.lighter = #2b313a
[One Dark]OR.colors.row.darker = #22252c
[One Dark]OR.colors.table.flash = #ffff803c
[One Dark]OR.colors.table.selection = #334266
[One Dark]OR.colors.flightData.textActive = #d4e6ff
[One Dark]OR.colors.flightData.textInactive = #aac9ff7f
[One Dark]OR.colors.multiCompEdit = #ffa5c8
[One Dark]OR.defaults.component.body = 150,175,255
[One Dark]OR.defaults.component.tubeFinSet = 150,184,254
[One Dark]OR.defaults.component.finSet = 150,184,255
[One Dark]OR.defaults.component.launchLug = 142,153,238
[One Dark]OR.defaults.component.railButton = 142,153,238
[One Dark]OR.defaults.component.internal = 181,128,151
[One Dark]OR.defaults.component.massObject = 210,210,210
[One Dark]OR.defaults.component.recoveryDevice = 220,90,90
[One Dark]OR.defaults.component.podSet = 190,190,235
[One Dark]OR.defaults.component.parallelStage = 210,180,195
[One Dark]OR.defaults.lineStyle.generic = SOLID
[One Dark]OR.defaults.lineStyle.massObject = DASHED
[One Dark]OR.colors.motor.border = #ffffffc8
[One Dark]OR.colors.motor.fill = #00000046
[One Dark]OR.colors.cg = #5585fd
[One Dark]OR.colors.cp = #ff486a
[One Dark]OR.colors.url = #abb9ff
[One Dark]OR.colors.componentTree.background = #2b2d33
[One Dark]OR.colors.componentTree.foreground = $Label.foreground
[One Dark]OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.dark
[One Dark]OR.colors.fin.gridMajor = #a4a4e0c5
[One Dark]OR.colors.fin.gridMinor = #8686c945
[One Dark]OR.colors.fin.point = #f27979ff
[One Dark]OR.colors.fin.selectedPoint = #e84e4eff
[One Dark]OR.colors.fin.bodyLine = #ffffff
[One Dark]OR.colors.fin.snapHighlight = #f14d4dff

[One_Dark]Tree.hash = #568AF2
[One_Dark]Tree.selectionBackground = #3E6CAD

[One_Dark]Slider.trackColor = #616365

[One_Dark]SplitPaneDivider.hoverColor = lighten(@background, 5%)

# Custom OpenRocket keys
[One_Dark]OR.ScrollPane.borderColor = #6e7275
[One_Dark]OR.colors.background = #2b2d33
[One_Dark]OR.colors.border = #a3a3a3cc
[One_Dark]OR.colors.text = $Label.foreground
[One_Dark]OR.colors.text.dim = #a5abb8
[One_Dark]OR.colors.text.disabled = #808080df
[One_Dark]OR.colors.textSelection.foreground = #ffffff
[One_Dark]OR.colors.textSelection.background = #3e6cad
[One_Dark]OR.colors.info = #c5c5fc
[One_Dark]OR.colors.warning = #ffe9bb
[One_Dark]OR.colors.error = #ffadad
[One_Dark]OR.colors.darkError = #ffb2b2
[One_Dark]OR.colors.row.lighter = #2b313a
[One_Dark]OR.colors.row.darker = #22252c
[One_Dark]OR.colors.table.flash = #ffff803c
[One_Dark]OR.colors.table.selection = #334266
[One_Dark]OR.colors.flightData.textActive = #d4e6ff
[One_Dark]OR.colors.flightData.textInactive = #aac9ff7f
[One_Dark]OR.colors.multiCompEdit = #ffa5c8
[One_Dark]OR.defaults.component.body = 150,175,255
[One_Dark]OR.defaults.component.tubeFinSet = 150,184,254
[One_Dark]OR.defaults.component.finSet = 150,184,255
[One_Dark]OR.defaults.component.launchLug = 142,153,238
[One_Dark]OR.defaults.component.railButton = 142,153,238
[One_Dark]OR.defaults.component.internal = 181,128,151
[One_Dark]OR.defaults.component.massObject = 210,210,210
[One_Dark]OR.defaults.component.recoveryDevice = 220,90,90
[One_Dark]OR.defaults.component.podSet = 190,190,235
[One_Dark]OR.defaults.component.parallelStage = 210,180,195
[One_Dark]OR.defaults.lineStyle.generic = SOLID
[One_Dark]OR.defaults.lineStyle.massObject = DASHED
[One_Dark]OR.colors.motor.border = #ffffffc8
[One_Dark]OR.colors.motor.fill = #00000046
[One_Dark]OR.colors.cg = #5585fd
[One_Dark]OR.colors.cp = #ff486a
[One_Dark]OR.colors.url = #abb9ff
[One_Dark]OR.colors.componentTree.background = #2b2d33
[One_Dark]OR.colors.componentTree.foreground = $Label.foreground
[One_Dark]OR.colors.visibility.hidden.foreground = $Tree.textForeground.hidden.dark
[One_Dark]OR.colors.fin.gridMajor = #a4a4e0c5
[One_Dark]OR.colors.fin.gridMinor = #8686c945
[One_Dark]OR.colors.fin.point = #f27979ff
[One_Dark]OR.colors.fin.selectedPoint = #e84e4eff
[One_Dark]OR.colors.fin.bodyLine = #ffffff
[One_Dark]OR.colors.fin.snapHighlight = #f14d4dff
